export const INPUT_UPDATE_VALUE = 'INPUT_UPDATE_VALUE';
export const GAME_STATUS = 'GAME_STATUS';
export const ERROR_STATUS = 'ERROR_STATUS';
export const PLAYER_UPDATE_VALUE = 'PLAYER_UPDATE_VALUE';
export const RESET = 'RESET';